# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('fat-tree', ['network','point-to-point','internet'])
    module.source = [
        'model/fat-tree.cc',
        'helper/fat-tree-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('fat-tree')
    module_test.source = [
        'test/fat-tree-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'fat-tree'
    headers.source = [
        'model/fat-tree.h',
        'helper/fat-tree-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

