# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('fat-tree-example', ['fat-tree','applications'])
    obj.source = 'fat-tree-example.cc'

