# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('hadoop', ['applications'])
    module.source = [
        'model/hadoop.cc',
        'model/hadoop-data-node.cc',
        'model/hadoop-name-node.cc',
        'model/hadoop-hdfs-client.cc',
        'helper/hadoop-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('hadoop')
    module_test.source = [
        'test/hadoop-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'hadoop'
    headers.source = [
        'model/hadoop.h',
        'model/hadoop-data-node.h',
        'model/hadoop-name-node.h',
        'model/hadoop-hdfs-client.h',
        'helper/hadoop-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

